set(PACKAGE_VERSION 0.73.1)

# Check whether the requested PACKAGE_FIND_VERSION is compatible
if (DEFINED PACKAGE_FIND_VERSION)
    if("${PACKAGE_FIND_VERSION_MAJOR}" EQUAL "0")
        if ("${PACKAGE_FIND_VERSION_MINOR}" EQUAL "73")
            set(PACKAGE_VERSION_EXACT TRUE)
        elseif("${PACKAGE_FIND_VERSION_MINOR}" LESS "73")
            set(PACKAGE_VERSION_COMPATIBLE TRUE)
        else()
            set(PACKAGE_VERSION_UNSUITABLE TRUE)
        endif()
    else()
        set(PACKAGE_VERSION_UNSUITABLE TRUE)
    endif()
else()
    message("No specific version of ZEDHUB defined. Building with 0.73.1")
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
endif()
